name: Trigger Azure DevOps Pipeline

on:
 push:
   branches:
    - main
jobs:
  trigger-pipeline:
   runs-on: ubuntu-latest
  
   steps:
   - name: Trigger Azure DevOps Pipeline
     uses: azure/pipeline@v1
     with:
      azure-devops-project-url: 'https://dev.azure.com/yenneprem0876DGV'
      azure-devops-token: $ {{ secrets.AZURE_DEVOPS_TOKEN }}
      azure-pipeline-name: 'pyenne.gitapp'